name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Windows build
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always
      GST_VERSION: 1.26.5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry + build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Cache GStreamer
        id: gst-cache
        uses: actions/cache@v4
        with:
          path: C:\gstreamer\1.0
          key: ${{ runner.os }}-gstreamer-devel-${{ env.GST_VERSION }}

      - name: Install / Setup GStreamer (devel only)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $ver  = "$env:GST_VERSION"
          $candidateRoots = @(
            'C:\gstreamer\1.0\msvc_x86_64',
            'C:\Program Files\gstreamer\1.0\msvc_x86_64'
          )
          $pkgCfg = $null
          foreach ($r in $candidateRoots) {
            if (Test-Path (Join-Path $r 'bin/pkg-config.exe')) { $pkgCfg = Join-Path $r 'bin/pkg-config.exe'; $root = $r; break }
          }
          if (-not $pkgCfg) {
            Write-Host "GStreamer devel $ver not cached. Downloading..."
            $base = "https://gstreamer.freedesktop.org/data/pkg/windows/$ver/msvc"
            $develMsi = "gstreamer-1.0-devel-msvc-x86_64-$ver.msi"
            Invoke-WebRequest "$base/$develMsi" -OutFile gst-devel.msi -UseBasicParsing
            Start-Process msiexec -ArgumentList '/i','gst-devel.msi','/qn','/norestart' -Wait
            # After install, re-detect
            foreach ($r in $candidateRoots) {
              if (Test-Path (Join-Path $r 'bin/pkg-config.exe')) { $pkgCfg = Join-Path $r 'bin/pkg-config.exe'; $root = $r; break }
            }
            if (-not $pkgCfg) { throw "pkg-config.exe still not found after installing GStreamer devel $ver" }
            Write-Host "Installed GStreamer devel $ver at $root"
          } else {
            Write-Host "Using cached GStreamer devel $ver at $root"
          }
          "GSTREAMER_ROOT=$root"        | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding ASCII
          "PKG_CONFIG_PATH=$root\lib\pkgconfig" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding ASCII
          "PATH=$root\bin;$env:PATH"    | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding ASCII
          & $pkgCfg --version

      - name: Build (release)
        run: cargo build --release --locked

      # (Optional) Add a test step here when tests are introduced
